### ISSUE TITLE
Fix Contacts page redirection

### ISSUE THREAD

**Issue by boddolk** [ScalHive/scalhive-content#110]
## Description
This is a bug when a user fills out their information on the `Contacts` feedback page, and then it `redirects them` to the en version of the site with a thank you message.

Button `Home page` at the en `thank-you` page redirects to the ua site version.

Button `Contact us` at the en  version redirects to the 404 page.

## Tasks
- [x] Fix `Contacts` page redirection
- [x] Fix `Home page` button redirection
- [x] Fix `Contact us` button redirection
