### ISSUE TITLE
Fix content inaccuracies

### ISSUE THREAD

**Issue by ya6lis** [ScalHive/scalhive-content#113]
## Tasks description

- Different dates on different language versions of the site.

![Image](https://github.com/user-attachments/assets/b5a30d2d-d1b9-41e3-b168-5182a058de37)
![Image](https://github.com/user-attachments/assets/e6e83dfe-5c3e-46d2-b8d9-00e4e577769b)

- Check the correct translation and styles in contacts form.
- Check the correct translation in navbar.
- Change email style in privacy page to look like in footer.

## Tasks

- [x] Different dates on different language versions of the site.
- [x] Check the correct translation and styles in contacts form.
- [x] Check the correct translation in navbar.
- [x] Change email style in privacy page to look like in footer.
