### ISSUE TITLE
Add CI configuration for Hugo

### ISSUE THREAD

**Issue by Nazarii-Melnyk** [ScalHive/scalhive-content#13]
## Tasks

- [x] Choose Hugo version to build website.
- [x] Create `hugo.yml` file in directory `.github/workflow/`.
- [x] Check CI results.
