### ISSUE TITLE
Hugo can't reach theme using URL

### ISSUE THREAD

**Issue by Nazarii-Melnyk** [ScalHive/scalhive-content#24]
## Description

After starting docker compose Hugo returns an error that it can't find theme module:
![image](https://github.com/TNTU-RS-internship/scalhive-content/assets/72742712/1511ef99-3687-4caa-9df1-5d48b8c39c63)

## Tasks
- [x] Investigate what's wrong
- [x] Fix module path in scalhive-theme. [Issue](https://github.com/TNTU-RS-internship/scalhive-theme/issues/7)
- [x] Solve the problem
