### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by Nazarii-Melnyk** [ScalHive/scalhive-content#52]
### Tasks
- [x] Add info in `about` sections  for scalhive [theme](url) and [content](url) repositories
- [x] Update CI/CD inmpementation info (requires solving question #47)
- [x] Update repository structure info
