### ISSUE TITLE
Update theme version into 1.2.0

### ISSUE THREAD

**Issue by Nazarii-Melnyk** [ScalHive/scalhive-content#55]
## Requirenments
- [x] [Stylize website](https://github.com/orgs/TNTU-RS-internship/projects/6/views/1?pane=issue&itemId=51250480) issue.

## Tasks
- [x] Update version of theme into `1.2.0` in go.mod file
- [x] Make changes in conf/content file to use new version of theme
