### ISSUE TITLE
Create docker-compose file

### ISSUE THREAD

**Issue by Nazarii-Melnyk** [ScalHive/scalhive-content#6]
## Tasks
- [x] Choose version of Hugo image for container
- [x] Create docker-compose.yml file to deploy website powered by Hugo locally in container
- [x] Check website deployment in docker container locally
