### ISSUE TITLE
Update theme version into v1.3.0

### ISSUE THREAD

**Issue by Nazarii-Melnyk** [ScalHive/scalhive-content#72]
## Requirenments
- [x] https://github.com/TNTU-RS-internship/scalhive-theme/issues/32
- [x] https://github.com/TNTU-RS-internship/scalhive-theme/issues/33

## Tasks
- [x] Update version of theme into `v2.0.0` in go.mod file
- [x] Make changes in conf/content files to use new version of theme
- [ ] Change urls in blog pages
