### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by Nazarii-Melnyk** [ScalHive/scalhive-content#73]
## Tasks
- [x]  https://github.com/TNTU-RS-internship/scalhive-theme/issues/36
- [x] Add info about tagging and release
- [x] Update CI/CD info
