### ISSUE TITLE
Update content in ua version of site

### ISSUE THREAD

**Issue by Nazarii-Melnyk** [ScalHive/scalhive-content#84]
## Description
- In `About us` page not all blocks was translated on ua. 
- At times, an inaccurate translation is found on the `blog pages`.
- In `Thank you page` now text is `'Thank you for message'`. Idea to change it to `'Thank you for your feedback'` for example. 

## Tasks
- [x] Translate all blocks in ua version of `'About us' page`.
- [x] Check and change ua translation in `blog pages`.
- [x] Change `Thank you page` text.
